---
apiVersion: v1
kind: Service
metadata:
  name: {{service.name}}
  namespace: {{build.profile.namespace}}
spec:
  selector:
    app: {{service.name}}
  ports:
    - protocol: 'TCP'
      port: {{service.targetPort}}
